version: '3.9'

services:
    d_carlo-mysql:
        image: mysql
        container_name: d_carlo-mysql
        hostname: d_carlo-mysql
        command: --default-authentication-plugin=mysql_native_password
        # restart: always
        cap_add:
        - SYS_NICE  # CAP_SYS_NICE
        ports: 
        - "3306:3306"
        env_file: # Environment Variables list
        - src/services/mysql/.env
        volumes: # At /databases/mysql/dumps are the .sql files to dump
        - "./src/services/mysql/mysql.cnf:/etc/mysql/conf.d/ne_my.cnf"
        - ./src/services/mysql/dumps:/docker-entrypoint-initdb.d
        - ./src/services/mysql/data:/var/lib/mysql
        networks:
        - d_carlo-network
    

networks:
    d_carlo-network:   